### ISSUE TITLE
JSON API for collections is broken

### ISSUE THREAD

**Issue by j-dornbusch** [samvera/hyrax#3202]
### Descriptive summary
When you try to fetch collection data through json API, you get an error with "undefined method `fields' for NilClass:Class".
Tested on fresh Hyrax development instance, 2.1.0, master branch.

### Rationale
We want to access to data by collection through Hyrax API as direct access to Fedora would ignore permissions.

### Expected behavior
An HTTP request to any collection page with .json extension (e.g. http://localhost:3000/collections/qr46r0806.json) should return valid JSON.

### Actual behavior
An HTTP request to any collection page with .json extension (e.g. http://localhost:3000/collections/qr46r0806.json) returns :
```
NoMethodError at /collections/qr46r0806.json
undefined method `fields' for NilClass:Class
```
hyrax/app/views/hyrax/base/show.json.jbuilder
```ruby
json.extract! @curation_concern, *[:id] + @curation_concern.class.fields.reject { |f| [:has_model].include? f }

json.version @curation_concern.etag
```
### Steps to reproduce the behavior

1. Log in and create a collection with name "Test"
2. Display the collection through `http://localhost:3000/collections/<coll-id>?locale=en`
3. Change URL to add JSON extension : `http://localhost:3000/collections/<coll-id>.json`

**Comment by jcoyne** [comment]
I believe this was a regression in https://github.com/samvera/hyrax/commit/18557e5ee4ca602d7a320b6fb91f3596326487f7 (collection types sprint)
