### ISSUE TITLE
Editing batch of works generates "NoMethodError in Hyrax::BatchEditsController#edit" error

### ISSUE THREAD

**Issue by jlhardes** [samvera/hyrax#5797]
### Descriptive summary

On nurax-pg, editing a batch of works displays a "NoMethodError in Hyrax::BatchEditsController#edit" error

### Expected behavior

Selecting multiple works on the Works page and clicking "Edit Selected" should bring me to an edit page

### Actual behavior

Selecting multiple works on the Works page and clicking "Edit Selected" generates an error message:

![Screen Shot 2022-08-12 at 10 54 55 AM](https://user-images.githubusercontent.com/3440166/184382360-ba0b6495-3aa0-46b7-b2da-2c1b87b62278.png)

### Steps to reproduce the behavior

1. On nurax-pg, navigate to Dashboard -> Works
2. Select one or more works on the Works page
3. Click the "Edit Selected" button
4. Observe error message

### Related work

#5461 Issue with initial report of batch work edit problem but error message was different

**Comment by jlhardes** [comment]
#4913 BatchEditsController needs to support valkyrie objects - code changes identified here might be part of the work that needs to happen to address this issue

**Comment by jlhardes** [comment]
Still seeing error message when selecting multiple works and trying to "Edit Selected" when testing locally on koppie.

**Comment by gamontoya** [comment]
@rjkati This now works on `Hyrax Version: 4.0.0.rc3`, but it fails with `Koppie v4.0.0.rc3`

**Hyrax:**

![HyraxEdit](https://github.com/samvera/hyrax/assets/4314914/0fa8268f-77b1-4f2a-af43-fbf8898c6b0d)

**Koppie:**

![batchEdit](https://github.com/samvera/hyrax/assets/4314914/0bc6612e-19a8-435e-9fab-c3cdddd70414)

**Comment by alishaevn** [comment]
I've created 2 GenericWork's on the koppie app and in the Hyrax app. trying to batch edit on Koppie showed me that the form thought it was editing at least one Monograph work. I don't have any Monograph works in my local apps. I also noticed that when I accessed the rails console for koppie, it couldn't return a count for GenericWorks, but it could for Hyrax.

``` bash
# KOPPIE
[3] pry(main)> GenericWork.all.count
NoMethodError: undefined method `all' for GenericWork:Class
from (pry):3:in `__pry__'

# HYRAX
[2] pry(main)> GenericWork.all.count
=> 2
```

![Screenshot 2023-05-25 at 4 18 47 PM](https://github.com/samvera/hyrax/assets/29032869/f19f058b-3267-4cd9-b698-5290558ac90c)

**Comment by alishaevn** [comment]
the [dassie GenericWork](https://github.com/samvera/hyrax/blob/main/.dassie/app/models/generic_work.rb) and [koppie GenericWork](https://github.com/samvera/hyrax/blob/main/.koppie/app/models/generic_work.rb) models are defined differently. The [dassie Monograph](https://github.com/samvera/hyrax/blob/main/.dassie/app/models/monograph.rb) and [koppie Monograph](https://github.com/samvera/hyrax/blob/main/.koppie/app/models/monograph.rb) models are defined the same however. to try and make sure things were as similar as possible between the two, I tried to make a monograph work in both apps, but the form for both failed with the error below.

<img width="1142" alt="image" src="https://github.com/samvera/hyrax/assets/29032869/136477a3-e409-4994-a2cc-c3edb4f3b951">

**Comment by alishaevn** [comment]
I merged `main` into the valykyrie_batch_edit branch and the batch edit works in koppie.

**Comment by alishaevn** [comment]
@dlpierce please refer to the comment above. the koppie app is working, but the hyrax app is not. is that your expectation? or do you have other work from this branch that hasn't been pushed?

![image](https://github.com/samvera/hyrax/assets/29032869/7a3962fb-b958-45f9-9a9c-c81ec15e5e3b)

**Comment by alishaevn** [comment]
the spec pipelines are still failing and I believe they're legitimate. I time boxed trying to solve this and I'm putting this down.
