### PR TITLE
CurationConcern.actor_factory does not need to be settable. Fixes #1398

### LINKED ISSUE #1398: Hyrax::CurationConcern.actor_factory not being set correctly
### Descriptive summary

Version: hyrax (1.0.3)

Traceback:

```
undefined method 'build' for nil:NilClass

vendor/bundle/ruby/2.3.0/gems/hyrax-1.0.3/app/services/hyrax/curation_concern.rb:13:in `actor'
vendor/bundle/ruby/2.3.0/gems/hyrax-1.0.3/app/controllers/concerns/hyrax/curation_concern_controller.rb:125:in `actor'
vendor/bundle/ruby/2.3.0/gems/hyrax-1.0.3/app/controllers/concerns/hyrax/curation_concern_controller.rb:45:in `create'
vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.2/lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.2/lib/abstract_controller/base.rb:186:in `process_action'
vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.2/lib/action_controller/metal/rendering.rb:30:in `process_action'
vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.2/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.2/lib/active_support/callbacks.rb:131:in `run_callbacks'
vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.2/lib/abstract_controller/callbacks.rb:19:in `process_action'
vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.2/lib/action_controller/metal/rescue.rb:20:in `process_action'
vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.2/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.2/lib/active_support/notifications.rb:166:in `block in instrument'
vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.2/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.2/lib/active_support/notifications.rb:166:in `instrument'
vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.2/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.2/lib/action_controller/metal/params_wrapper.rb:252:in `process_action'
vendor/bundle/ruby/2.3.0/gems/activerecord-5.1.2/lib/active_record/railties/controller_runtime.rb:22:in `process_action'
vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.2/lib/abstract_controller/base.rb:124:in `process'
vendor/bundle/ruby/2.3.0/gems/actionview-5.1.2/lib/action_view/rendering.rb:30:in `process'
vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.2/lib/action_controller/metal.rb:189:in `dispatch'
vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.2/lib/action_controller/metal.rb:253:in `dispatch'
vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.2/lib/action_dispatch/routing/route_set.rb:49:in `dispatch'
vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.2/lib/action_dispatch/routing/route_set.rb:31:in `serve'
vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.2/lib/action_dispatch/journey/router.rb:46:in `block in serve'
vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.2/lib/action_dispatch/journey/router.rb:33:in `each'
vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.2/lib/action_dispatch/journey/router.rb:33:in `serve'
vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.2/lib/action_dispatch/routing/route_set.rb:832:in `call'
vendor/bundle/ruby/2.3.0/gems/warden-1.2.7/lib/warden/manager.rb:36:in `block in call'
vendor/bundle/ruby/2.3.0/gems/warden-1.2.7/lib/warden/manager.rb:35:in `catch'
vendor/bundle/ruby/2.3.0/gems/warden-1.2.7/lib/warden/manager.rb:35:in `call'
vendor/bundle/ruby/2.3.0/gems/rack-2.0.3/lib/rack/etag.rb:25:in `call'
vendor/bundle/ruby/2.3.0/gems/rack-2.0.3/lib/rack/conditional_get.rb:38:in `call'
vendor/bundle/ruby/2.3.0/gems/rack-2.0.3/lib/rack/head.rb:12:in `call'
vendor/bundle/ruby/2.3.0/gems/rack-2.0.3/lib/rack/session/abstract/id.rb:232:in `context'
vendor/bundle/ruby/2.3.0/gems/rack-2.0.3/lib/rack/session/abstract/id.rb:226:in `call'
vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.2/lib/action_dispatch/middleware/cookies.rb:613:in `call'
vendor/bundle/ruby/2.3.0/gems/active-fedora-11.4.0/lib/active_fedora/ldp_cache.rb:26:in `call'
vendor/bundle/ruby/2.3.0/gems/flipflop-2.3.1/lib/flipflop/feature_cache.rb:12:in `call'
vendor/bundle/ruby/2.3.0/gems/activerecord-5.1.2/lib/active_record/migration.rb:556:in `call'
vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.2/lib/action_dispatch/middleware/callbacks.rb:26:in `block in call'
vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.2/lib/active_support/callbacks.rb:97:in `run_callbacks'
vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.2/lib/action_dispatch/middleware/callbacks.rb:24:in `call'
vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.2/lib/action_dispatch/middleware/executor.rb:12:in `call'
vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.2/lib/action_dispatch/middleware/debug_exceptions.rb:59:in `call'
vendor/bundle/ruby/2.3.0/gems/web-console-3.5.1/lib/web_console/middleware.rb:135:in `call_app'
vendor/bundle/ruby/2.3.0/gems/web-console-3.5.1/lib/web_console/middleware.rb:20:in `block in call'
vendor/bundle/ruby/2.3.0/gems/web-console-3.5.1/lib/web_console/middleware.rb:18:in `catch'
vendor/bundle/ruby/2.3.0/gems/web-console-3.5.1/lib/web_console/middleware.rb:18:in `call'
vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.2/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
vendor/bundle/ruby/2.3.0/gems/railties-5.1.2/lib/rails/rack/logger.rb:36:in `call_app'
vendor/bundle/ruby/2.3.0/gems/railties-5.1.2/lib/rails/rack/logger.rb:24:in `block in call'
vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.2/lib/active_support/tagged_logging.rb:69:in `block in tagged'
vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.2/lib/active_support/tagged_logging.rb:26:in `tagged'
vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.2/lib/active_support/tagged_logging.rb:69:in `tagged'
vendor/bundle/ruby/2.3.0/gems/railties-5.1.2/lib/rails/rack/logger.rb:24:in `call'
vendor/bundle/ruby/2.3.0/gems/sprockets-rails-3.2.0/lib/sprockets/rails/quiet_assets.rb:13:in `call'
vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.2/lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.2/lib/action_dispatch/middleware/request_id.rb:25:in `call'
vendor/bundle/ruby/2.3.0/gems/rack-2.0.3/lib/rack/method_override.rb:22:in `call'
vendor/bundle/ruby/2.3.0/gems/rack-2.0.3/lib/rack/runtime.rb:22:in `call'
vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.2/lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.2/lib/action_dispatch/middleware/executor.rb:12:in `call'
vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.2/lib/action_dispatch/middleware/static.rb:125:in `call'
vendor/bundle/ruby/2.3.0/gems/rack-2.0.3/lib/rack/sendfile.rb:111:in `call'
vendor/bundle/ruby/2.3.0/gems/railties-5.1.2/lib/rails/engine.rb:522:in `call'
/usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:97:in `process_request'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:160:in `accept_and_process_next_request'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:113:in `main_loop'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:416:in `block (3 levels) in start_threads'
/usr/lib/ruby/vendor_ruby/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'

Parameters:

{"utf8"=>"✓",
 "authenticity_token"=>"0a/Dl5NzILHmGcJrD2n9X2qiZRF0LwKI5MnodDaJpbMRqsIjqYF3JsD+cLBIu9iyBl3m76ntFZh+HYC8QmVo0g==",
 "composition"=>
  {"title"=>["asdf"],
   "creator"=>["asdf"],
   "keyword"=>["asdf"],
   "rights"=>["http://creativecommons.org/licenses/by/3.0/us/"],
   "contributor"=>[""],
   "description"=>[""],
   "publisher"=>[""],
   "date_created"=>[""],
   "subject"=>[""],
   "language"=>[""],
   "identifier"=>[""],
   "based_near"=>[""],
   "related_url"=>[""],
   "source"=>[""],
   "resource_type"=>[""],
   "admin_set_id"=>"admin_set/default",
   "member_of_collection_ids"=>[""],
   "visibility"=>"open",
   "visibility_during_embargo"=>"restricted",
   "embargo_release_date"=>"2017-07-26",
   "visibility_after_embargo"=>"open",
   "visibility_during_lease"=>"open",
   "lease_expiration_date"=>"2017-07-26",
   "visibility_after_lease"=>"restricted"},
 "uploaded_files"=>["2"],
 "new_user_name_skel"=>"",
 "new_user_permission_skel"=>"none",
 "new_group_name_skel"=>"Select a group",
 "new_group_permission_skel"=>"none",
 "agreement"=>"1",
 "locale"=>"en"}
```

### Rationale

When I attempt to create a work through the hyrax GUI at https://localhost/concern/work/new?locale=en I get the following error when I click save after adding metadata and attaching a file.
`undefined method 'build' for nil:NilClass` line 13 in hyrax-1.0.3/app/services/hyrax/curation_concern.rb

### Expected behavior

Application should create a work object and redirect to the work's show page.

### Actual behavior

Application throws `undefined method 'build' for nil:NilClass` exception
It seems as though `Hyrax::CurationConcern.actor_factory` is not being set. It should be set here
https://github.com/samvera/hyrax/blob/v1.0.3/lib/hyrax/engine.rb#L70

### Steps to reproduce the behavior

1. Navigate to the /concern/work/new page in the hyrax application
2. Enter metadata
3. Attach file
4. Click "Save"

Note: A work can be successfully created by setting:
`Hyrax::CurationConcern.actor_factory = Hyrax::ActorFactory` immediately before the `actor_factory.build` call here:
https://github.com/samvera/hyrax/blob/v1.0.3/app/services/hyrax/curation_concern.rb#L13

### Related work

Link to related tickets or prior related work here.

### PR DESCRIPTION
**Pull request by jcoyne**
Fixes #1398

### CODE REVIEW

**Comment by whunter** [comment]
I'll test this afternoon. Thank you all for your attention and effort on this.

**Comment by whunter** [comment]
Hi,
I tested this out and I got this error: https://gist.github.com/whunter/505e8a61099a8cb70d4171eeaa8c8485

app/controllers/concerns/hyrax/curation_concern_controller.rb:125 calls actor with 2 arguments
`@actor ||= Hyrax::CurationConcern.actor(curation_concern, current_ability)`

I see that this is to be merged into Master. Will it also work on 1.0.3? I only ask because the diffs don't match up with what I'm seeing in 1.0.3. For instance in lib/hyrax/engine.rb `Hyrax::CurationConcern.actor_factory` is set on line 70 and the `config.to_prepare` block that is to be removed in this PR doesn't exist.

I really appreciate your efforts on this. I know that you all are busy.

**Comment by mjgiarlo** [comment]
@whunter OK, can you try the following patch in `1-0-stable`?

Change the following two lines https://github.com/samvera/hyrax/blob/v1.0.3/app/services/hyrax/curation_concern.rb#L3-L4 to

```ruby
  # @return [ActionDispatch::MiddlewareStack]
  def self.actor_factory
    Hyrax::ActorFactory
  end
```

And remove the following line from the engine: https://github.com/samvera/hyrax/blob/v1.0.3/lib/hyrax/engine.rb#L70

I think that's how we would backport this PR from `master` to `1-0-stable` if it winds up working for you, @whunter.

**Comment by whunter** [comment]
Hi @mjgiarlo , I just submitted this: https://github.com/samvera/hyrax/pull/1423 I tested it and it works for me. It's basically what you suggested earlier. Moving the call up. The difference seemed to be putting the call in a to_prepare block.

**Comment by mjgiarlo** [comment]
@jcoyne do you have thoughts on the solution @whunter proposed in #1423 relative to this PR? Would we rather have this code in curation_concern.rb or engine.rb? Let's settle that and then roll out the same solution to both `master` and `1-0-stable` to reduce drift between the branches.

**Comment by jcoyne** [comment]
@mjgiarlo I think this change makes it easier to understand and follows closer to how Rails initializes the Rack middleware stack.  #1423 does look like it would fix the reported issue though.  My preferred course would be to merge this and backport for 1.x

**Comment by whunter** [comment]
@jcoyne I tested this earlier and got the following error:
https://gist.github.com/whunter/505e8a61099a8cb70d4171eeaa8c8485
I commented on it above.
Would the patch that @mjgiarlo suggested above be an acceptable solution, since actor_factory is set in https://github.com/samvera/hyrax/blob/v1.0.3/app/services/hyrax/curation_concern.rb ? If so, I can test it out to make sure it fixes the issue that I'm seeing.

**Comment by mjgiarlo** [comment]
@whunter Yes, you can't backport this change exactly to `1-0-stable`. Try my patch in `1-0-stable` if you could. If it works, I will merge this PR and backport it (with the changes that you'd be testing).

**Comment by jcoyne** [comment]
I'm happy with #1423 for 1-0-stable.

**Comment by mjgiarlo** [comment]
@whunter lmk when you get a chance to test the patch above with `1-0-stable`

**Comment by whunter** [comment]
@mjgiarlo The patch you suggested https://github.com/samvera/hyrax/pull/1409#issuecomment-320022023 works great! :)

**Comment by mjgiarlo** [comment]
@whunter OK, then I'm going to merge this PR and backport it as the patch in https://github.com/samvera/hyrax/pull/1409#issuecomment-320022023 in a couple minutes. Thanks!
